### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by FGS-BMarkham** [Killfile/DecoratorValidation#2]
I can't compile the `DecoratorValidationTests` project because the following files are missing from the repo:
- `DecoratorValidationTests\StringValidation\StringValidator_BlackListTests.cs`
- `DecoratorValidationTests\StringValidation\StringValidator_ExpectedStringTests.cs`

**Comment by Killfile** [comment]
Addressed in 07c20245fa7d50a7e816f26614b01f601eb60df3
