### ISSUE TITLE
Lambda Is Misspelled

### ISSUE THREAD

**Issue by FGS-BMarkham** [Killfile/DecoratorValidation#3]
"Lambda" appears to be misspelled as "lamda" everywhere.

I'm happy to submit a PR to fix it, but I need you to look into #2 first.

**Comment by Killfile** [comment]
Fixed in f64ebf4f8fd969b3e2dc6b70d55490f68170107b

**Comment by FGS-BMarkham** [comment]
This wasn't addressed by f64ebf4. #2 is the one you addressed with that.
